### ISSUE TITLE
Consider adding queryOne queryAll

### ISSUE THREAD

**Issue by gajus** [namshi/node-mysql2-promise#5]
```js
db.queryOne = (...args) => {
    return db
        .query(...args)
        .then((result) => {
            return result[0][0];
        });
};

db.queryAll = (...args) => {
    return db
        .query(...args)
        .then((result) => {
            return result[0];
        });
};
```

This makes using ES7 async/ await a lot more succinct.

```js
latestPage = await db.queryOne('SELECT `id`, `name` FROM `page` ORDER BY `id` DESC');

// {id: 1, name: 'Foo'}
latestPage;
```

**Comment by gajus** [comment]
`queryMany` would probably be a better name, though than `queryAll`.

**Comment by gajus** [comment]
@namshi thoughts?

**Comment by unlucio** [comment]
## queryAll/queryMany
I'm not sure what do you actually mean with `queryOne` since a possibile implementation of `queriAll` would be something like:

```javascript
db.queryAll = function (...args) {
  var queries = args.map((query) =>  {
    return db.query(query);
  });

  return Promise.all(queries);
} 
```
This looks more like a simple modules to add promisses sugar on top of mysql2, imho adding`queryAll()` (imho would better reflect the underlying use of `Promise.all()`) might be slightly an overkill since the behaviour could be both parallel or sequencial depending by your needs: I want 10 queries to be executed together VS someone that would rather have them executed one by one.

## await
Es7 is still been discussed, while the world is still catching up with Es6, and if you want/plan to use async/await you'll probably not need this kind of libs any more if your use of promisses is just for control flow.

## Overall:
I lack to understand what's your point :P, anyway feel free to open a PR with those 5 lines if you feel `queryAll()` can be very useful :)
